config/routes.rb
# Rails.application.routes.draw do
  # get 'user_sessions/new'
  # get 'user_sessions/create'
#   get 'sessions/new'
#   get 'sessions/create'
#   get 'sessions/destroy'
#   resources :users, only: [:new, :create, :index, :show]
#   resources :sessions, only: [:new, :create, :destroy]
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Defines the root path route ("/")
#   # root "posts#index"
# end

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/secret'
  get 'pages/dashboard'
  get '/rfqs/new', to: "rfqs#new"
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :rfqs, only: [:new, :create, :show, :edit] do
    resources :quotes, only: [:new, :create, :edit, :update]
  end
  resources :quotes
  resources :items, only: [:new, :create]
end

app/models/rfq.rb
class Rfq < ApplicationRecord
    belongs_to :user

    has_many :items, dependent: :destroy, inverse_of: :rfq, index_errors: true
    accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
    
    has_many :quotes, dependent: :destroy, inverse_of: :rfq
    accepts_nested_attributes_for :quotes

    validates :pickup_name, presence: true
    validates :pickup_street_address, presence: true
    validates :pickup_city, presence: true
    validates :pickup_postal, presence: true
    validates :pickup_state, presence: true
    validates :pickup_country, presence: true

    validates :shipto_name, presence: true
    validates :shipto_street_address, presence: true
    validates :shipto_city, presence: true
    validates :shipto_postal, presence: true
    validates :shipto_state, presence: true
    validates :shipto_country, presence: true

    validates :pickup_date, :delivery_date, presence: true
    # validate :delivery_date_after_pickup_date

    validates :items, length: {minimum: 1, message: "Must contain at least 1 item"}

    validates_associated :items
end

app/controllers/rfqs_controller.rb
class RfqsController < ApplicationController
  before_action :set_fields, only: %i[new create]

  def new
    @rfq = Rfq.new#; @rfq.items.build;
    # 2.times {@rfq.items.build}
    @user = User.new
  end

  def create
    @rfq = Rfq.create(rfq_params)

    if @rfq.valid?
      @rfq.save
      session[:notice] = "Rfq Created"
      redirect_to pages_dashboard_path
    else
      # flash[:alert] = "Error - Please try again"
      render :new, status: :unprocessable_content
    end
  end

  def edit
    @rfq = Rfq.find(params[:id])
    @quotes = @rfq.quotes
  end

  def update
    @rfq = Rfq.find(params[:id])
  end

  def destroy
    @rfq.destroy
    respond_to do |format|
      format.html {redirect_to user_url}
      format.json {head :no_content}
    end
  end

  def set_fields
    @user_array = User.all.map {|user| [user.name, user.id]}
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def rfq_params
    params.require(:rfq).permit(:pickup_name, :pickup_street_address, :pickup_city_area, :pickup_city, :pickup_county, :pickup_state, :pickup_postal, :pickup_country,
                                :shipto_name, :shipto_street_address, :shipto_city_area, :shipto_city, :shipto_county, :shipto_state, :shipto_postal, :shipto_country,
                                :pickup_date, :delivery_date, :state, :user_id,
                                :items_attributes => [:id, :_destroy, :name, :length, :width, :height, :weight, :description, :special_conditions],
                                :quotes_attributes => [:id, :_destroy, :cost, :special_conditions, :state, :rfq_id, :user_id])
  end

end

app/views/rfqs/_form.html.erb
<!-- <%= form_for(@rfq) do |f| %>
    <% if @rfq.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@rfq.errors.count, "error") %>
                prohibited this rfq from being saved:</h2>
            <ul>
                <%= @rfq.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.label :pickup_name, "Pickup Name" %>
        <%= f.text_field :pickup_name %>
    </div>
    Items:
    <%= submit_tag "Add Item", :type => 'button', :id => 'addItemButton', :onclick => "addItemFields"%>
    <br>
    <div id="itemsHeader" style="display:none"> Item Information: </div>
    <br>
    <fieldset id="itemsList"></fieldset>
<% end %> -->

<%= form_for(@rfq) do |f| %>
    <div class="form-inputs">
        <%= f.text_field :pickup_name %>
    </div>
    
<% end %>

app/views/rfqs/_item_fields.html.erb
<div class="item-field">
  <br>
  <%# <% index = f.index %>
  <%# <%= index_errors %>

  <% index = @rfq.items.length %>
  <%= index %>

  <% invalid = @rfq.errors.include?(:item) %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, class: "form-control" %>
  <% if invalid %>
      <div class="invalid-feedback d-block">
          <% f.errors.full_messages_for(:item.name).each do |error_message| %>
              <%= error_message %>
          <% end %>
      </div>
  <% end %>
  
  <br>
  <%= f.label :length, "Length (m)"%>
  <%= f.number_field :length, step: 0.01, class: "form-control"%>
  <br>
  <%= f.label :width, "Width (m)", style: "display: block" %>
  <%= f.number_field :width, step: 0.01, class: "form-control"%>
  <br>
  <%= f.label :height, "Height (m)", style: "display: block" %>
  <%= f.number_field :height, step: 0.01, class: "form-control"%>
  <br>
  <%= f.label :weight, "Weight (kg)", style: "display: block" %>
  <%= f.number_field :weight, step: 0.01, class: "form-control"%>
  <br>
  <%= f.label :description, "Description", style: "display: block" %>
  <%= f.text_area :description, class: "form-control" %>
  <br>
  <%= f.label :special_conditions, "Notes/Special Conditions", style: "display: block" %>
  <%= f.text_area :special_conditions, class: "form-control" %>
  <br>
    <%= link_to_remove_association "Remove Item", f %>
  <br>
</div>

<!-- Make nicer for the fields to be added-->

app/views/rfqs/_quote_fields.html.erb
<!--Fields to select users to send quote to-->
<div class="quote-field">
    <br>
    
    <%= f.collection_select :user_id, User.where("NOT id=#{current_user.id}"), :id, :name, {prompt: ''} %>

    <%= f.hidden_field :cost, value: 0 %>
    <%= f.hidden_field :special_conditions, value: "" %>
    <%= f.hidden_field :state, value: nil %>
    <%= f.hidden_field :quote_submitted, value: nil %>

    <%= link_to_remove_association "Remove Requestee", f %>
    
    <br>
</div>

app/views/rfqs/_update_quote_fields.html.erb
<div class="card">
    <% f.hidden_field :user_id %>
    <%# <%= User.find(:user_id) %>

    <%= f.label :cost %>
    <%= f.text_field :cost, class: "uneditable-input", :readonly => true %>
</div>

app/views/rfqs/edit.html.erb
<h1>View Quotes</h1>

<div class="row">
    <div class="column side"></div>
    <div class="column middle">
        <h3>Quotes</h3>
        <div class="cards">
            <% @quotes.each do |quote| %>
                <div class="card">
                    <%= User.find(quote.user_id).name %> <br>
                    <% if quote.quote_submitted == nil || quote.quote_submitted == false %>
                        No Quote Submitted <br>
                    <% else %> 
                        Cost: <%= quote.cost %> <br>
                        <% if quote.special_conditions != "" %>
                            Special Conditions: <%= quote.special_conditions %>
                        <% end %>
                    <% end %>

                    <div class="center-screen">
                        <% if @rfq.state != true %>
                            <%= link_to "Select Quote", edit_rfq_quote_path(@rfq, quote) %>
                        <% else %>
                            <% if quote.state != true %>
                                Quote not selected
                            <% else %>
                                Quote selected
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>

        <br>
        
        <h2>Request For Quote Information</h2>

        <div class="cards2column">
            <div class="card">
                <h3>Pickup Information</h3>
                Name: <%= @rfq.pickup_name %> <br>
                Street Address: <%= @rfq.pickup_street_address %> <br>
                City Area: <%= @rfq.pickup_city_area %> <br>
                City: <%= @rfq.pickup_city %> <br>
                County: <%= @rfq.pickup_county %> <br>
                State/Province: <%= @rfq.pickup_state %> <br>
                Country: <%= @rfq.pickup_country %> <br>
                ZIP/Postal: <%= @rfq.pickup_postal %> <br>
                Date: <%= @rfq.pickup_date %> 
            </div>

            <div class="card">
                <h3>Dropoff Information</h3>
                Name: <%= @rfq.shipto_name %> <br>
                Street Address: <%= @rfq.shipto_street_address %> <br>
                City Area: <%= @rfq.shipto_city_area %> <br>
                City: <%= @rfq.shipto_city %> <br>
                County: <%= @rfq.shipto_county %> <br>
                State/Province: <%= @rfq.shipto_state %> <br>
                Country: <%= @rfq.shipto_country %> <br>
                ZIP/Postal<%= @rfq.shipto_postal %> <br>
                Date: <%= @rfq.delivery_date %> <br>
            </div>
        </div>

        <br>
        <br>

        <h3>Items</h3>
        <div class="cards">
            <% @rfq.items.each do |item| %>
                <div class="card">
                    <fieldset>
                        Name: <%= item.name %> <br>
                        Description: <%= item.description %> <br>
                        Length (m): <%= item.length %> <br>
                        Width (m): <%= item.width %> <br>
                        Height (m): <%= item.height %> <br>
                        Widght (kg): <%= item.weight %> <br>
                    </fieldset>
                </div>
            <% end %>
        </div>
    </div>
</div>

<%# Create popup for verifying selected quote and set RFQ state to true to close any other things
https://duckduckgo.com/?q=ruby+on+rails+popups&t=ffab&atb=v250-1&ia=web
https://www.youtube.com/watch?v=1c_tHifJVRI
https://medium.com/@hienviluong125/ruby-on-rails-creating-pop-ups-with-stimulus-without-external-javascript-libraries-7ec01cd6ddd7 %>

app/views/rfqs/new.html.erb
<div class="row">
    <div class="column side">
        <h2 style="position: sticky; top: 5%; padding-left: 8%;">Request Quotes</h2>
    </div>
    <div class="column middle">
<!-- https://guides.rubyonrails.org/form_helpers.html#building-complex-forms
https://kylerego.github.io/one-way-to-add-and-remove-form-fields-on-the-fly-in-rails -->
<%= form_with model: @rfq, url: rfqs_path do |f| %>

    <%= @rfq.errors.full_messages %>

    <fieldset>
        <h3>Items:</h3>
        <div data-controller="nested-rondo" data-nested-rondo-field-class-value="item-field">
            <%= f.fields_for :items do |item| %>
                <%= render "item_fields", f: item, :locals => {f: item, index: item.index} %>
            <% end %>

            <div class="links">
                <%= link_to_add_association "Add Item", f, :items, class: "form-control" %>
            </div>
            <p data-nested-rondo-target="fieldContain" class="cards">

            </p>
        </div>
    </fieldset>

    <br>

    <fieldset>
        <h3>Users to Request Quote:</h3>
        <div data-controller="nested-rondo" data-nested-rondo-field-class-value="quote-field">
            <%= f.fields_for :quotes do |quote| %>
                <%= render "quote_fields", f: quote %>
            <% end %>
            <div class="links">
                <%= link_to_add_association "Add Requestee", f, :quotes, class: "form-control" %>
            </div>
            <p data-nested-rondo-target="fieldContain">

            </p>
        </div>
    </fieldset>

    <br>

    <fieldset class="cards2column">
        <div>

            <h2>
                Pickup Address:
            </h2>
            
            <p>
                <% invalid = @rfq.errors.include?(:pickup_name) %>

                <%= f.label :pickup_name, "Name" %>
                <%= f.text_field :pickup_name, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_name).each do |error_message| %>
                            <%= error_message %>
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:pickup_street_address) %>

                <%= f.label :pickup_street_address, "Street Address" %>
                <%= f.text_field :pickup_street_address, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_street_address).each do |error_message| %>
                            <%# <%= error_message %>
                            Street Address Cannot be Blank
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <%= f.label :pickup_city_area, "City Area" %> 
                <%= f.text_field :pickup_city_area, class: "form-control" %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:pickup_city) %>

                <%= f.label :pickup_city, "City"%> 
                <%= f.text_field :pickup_city, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_city).each do |error_message| %>
                            <%# <%= error_message %>
                            City Is Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <%= f.label :pickup_county, "County" %> 
                <%= f.text_field :pickup_county, class: "form-control" %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:pickup_postal) %>
                
                <%= f.label :pickup_postal, "Postal/ZIP Code" %> 
                <%= f.text_field :pickup_postal, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_postal).each do |error_message| %>
                            <%# <%= error_message %>
                            Postal/ZIP Code Is Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:pickup_state) %>

                <%= f.label :pickup_state, "Province/State" %> 
                <%= f.text_field :pickup_state, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_state).each do |error_message| %>
                            <%# <%= error_message %>
                            Province/State Is Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:pickup_country) %>

                <%= f.label :pickup_country, "Country" %> 
                <%= f.text_field :pickup_country, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:pickup_country).each do |error_message| %>
                            <%# <%= error_message %>
                            Country Is Required
                        <% end %>
                    </div>
                <% end %>
            </p>
        </div>

        <div>

            <h2>
                Ship To Address:
            </h2>
            
            <p>
                <% invalid = @rfq.errors.include?(:shipto_name) %>

                <%= f.label :shipto_name, "Name" %>
                <%= f.text_field :shipto_name, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_name).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:shipto_street_address) %>

                <%= f.label :shipto_street_address, "Street Address" %>
                <%= f.text_field :shipto_street_address, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_street_address).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <%= f.label :shipto_city_area, "City Area" %> 
                <%= f.text_field :shipto_city_area, class: "form-control" %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:shipto_city) %>

                <%= f.label :shipto_city, "City"%> 
                <%= f.text_field :shipto_city, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_city).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <%= f.label :shipto_county, "County" %>
                <%= f.text_field :shipto_county, class: "form-control" %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:shipto_postal) %>

                <%= f.label :shipto_postal, "Postal/ZIP Code" %>
                <%= f.text_field :shipto_postal, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_postal).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:shipto_state) %>

                <%= f.label :shipto_state, "Province/State" %>
                <%= f.text_field :shipto_state, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_state).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

            <p>
                <% invalid = @rfq.errors.include?(:shipto_country) %>

                <%= f.label :shipto_country, "Country" %>
                <%= f.text_field :shipto_country, class: "form-control #{'is-invalid' if invalid}" %>
                <% if invalid %>
                    <div class="invalid-feedback d-block">
                        <% @rfq.errors.full_messages_for(:shipto_country).each do |error_message| %>
                            <%# <%= error_message %>
                            Required
                        <% end %>
                    </div>
                <% end %>
            </p>

        </fieldset>    
        
        <h2>Dates</h2>
        <fieldset class="cards2column">
            <div>
                <p>
                    <% invalid = @rfq.errors.include?(:pickup_date) %>

                    <%= f.label :pickup_date, "Pick Up Date" %> 
                    <%= f.date_field :pickup_date, class: "form-control #{'is-invalid' if invalid}" %>
                    <% if invalid %>
                        <div class="invalid-feedback d-block">
                            <% @rfq.errors.full_messages_for(:pickup_date).each do |error_message| %>
                                <%# <%= error_message %>
                                Required
                            <% end %>
                        </div>
                    <% end %>
                </p>
            </div>

            <div>
                <p>
                    <%= f.label :delivery_date, "Delivery Date" %> 
                    <%= f.date_field :delivery_date, class: "form-control #{'is-invalid' if invalid}" %>
                </p>
            </div>
        </div>
    </fieldset>

    <br>
    
    <fieldset>
    </fieldset>
    
    <%= f.hidden_field :state, value: nil %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit "Create Request", class: "form-control" %>

<% end %>
</div>
</div>