config/routes.rb
# Rails.application.routes.draw do
  # get 'user_sessions/new'
  # get 'user_sessions/create'
#   get 'sessions/new'
#   get 'sessions/create'
#   get 'sessions/destroy'
#   resources :users, only: [:new, :create, :index, :show]
#   resources :sessions, only: [:new, :create, :destroy]
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Defines the root path route ("/")
#   # root "posts#index"
# end

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/secret'
  get 'pages/dashboard'
  get '/rfqs/new', to: "rfqs#new"
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :rfqs, only: [:new, :create, :show, :edit] do
    resources :quotes, only: [:new, :create, :edit, :update]
  end
  resources :quotes
  resources :items, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password :password, validations: true
    validates :name, presence: true, uniqueness: true

    has_many :rfqs
    has_many :quotes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:notice] = "User Created Successfully"
            redirect_to users_path
        else
            flash[:alert] = "Error - Please try again to create an account"
            render :new, status: :unprocessable_entity
            # redirect_to new_user_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<h1>Users#Index</h1>

<%= link_to 'New User', new_user_path %>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>Users#new</h1>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= content_tag :h1, current_user.welcome %>
<%= link_to "Sign Out", sessions_path, method:"delete" %>