config/routes.rb
# Rails.application.routes.draw do
  # get 'user_sessions/new'
  # get 'user_sessions/create'
#   get 'sessions/new'
#   get 'sessions/create'
#   get 'sessions/destroy'
#   resources :users, only: [:new, :create, :index, :show]
#   resources :sessions, only: [:new, :create, :destroy]
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Defines the root path route ("/")
#   # root "posts#index"
# end

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/secret'
  get 'pages/dashboard'
  get '/rfqs/new', to: "rfqs#new"
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :rfqs, only: [:new, :create, :show, :edit] do
    resources :quotes, only: [:new, :create, :edit, :update]
  end
  resources :quotes
  resources :items, only: [:new, :create]
end

app/views/pages/dashboard.html.erb
<h1 style="padding-left: 2%;">Welcome to your Dashboard, <%= current_user.name %></h1>
<!---<h1><%= current_user.id %> | <%= current_user.password_digest %></h1>--->

<div class="row">
    <div class="column side">
    </div>

    <div class="column middle">
        <h2>Existing RFQs</h2>
        <!-- 
            <h3><%= link_to "Create new RFQ", new_rfq_path %></h3>
        -->
        <table style="width:100%">
            <tr>
                <th>Pickup Name</th>
                <th>Pickup Street Address</th>
                <th>Dropoff Street Address</th>
                <th>Pickup Date</th>
                <th>Delivery Date</th>
                <th>View Quotes</th>
            </tr>
        <% @rfq_data.each do |data| %>
            <tr>
                <td><%= data.pickup_name %></td>
                <td><%= data.pickup_street_address %></td>
                <td><%= data.shipto_street_address %></td>
                <td><%= data.pickup_date %></td>
                <td><%= data.delivery_date %></td>
                <td><%= link_to "View Quotes", edit_rfq_path(data) %></td>
            </tr>
        <% end %>
        </table>

        <br>

        <h3>Quote Requests</h3>
        <table style="width: 100%;">
            <tr>
                <th>Requestee Name</th>
                <th>Pickup Street Address</th>
                <th>Dropoff Street Address</th>
                <th>Status</th>
            </tr>
        <% @quote_request_data.each do |data| %>
            <tr>
                <td><%= User.find(Rfq.find(data.rfq_id).user_id).name %></td>
                <td><%= Rfq.find(data.rfq_id).pickup_street_address %></td>
                <td><%= Rfq.find(data.rfq_id).shipto_street_address %></td>
                <td>
                    <% if !data[:quote_submitted] %>
                        <%= link_to "Create Quote", edit_quote_path(data) %>
                    <% else %>
                        <% if Rfq.find(data.rfq_id).state != true %>
                            <%= link_to "Under Consideration", edit_quote_path(data) %>
                        <% else %>
                            <% if data[:state] %>
                                <%= link_to "Quote Selected", edit_quote_path(data) %>
                            <% else %>
                                <%= link_to "Quote Declined", edit_quote_path(data) %>
                            <% end %>
                        <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
        </table>
    </div>
    <div class="column side">
    </div>
</div>

app/views/pages/index.html.erb
<% if current_user %>
    <h1>Welcome, <%= current_user.name %></h1>
    <%= link_to 'Log out', user_session_path(current_user), data: {turbo_method: :delete} %> <br>
<% else %>
    <h1>This is the index page</h1>
    <%= link_to 'Login', new_user_session_path %> <br>
<% end %>
<%= link_to 'Secret Page', '/pages/secret' %> <br>
<%= link_to 'Dashboard', '/pages/dashboard'%> <br>
<%= link_to 'Create User', new_user_path %>

app/views/pages/secret.html.erb
<h1>This is a secret page</h1>