config/routes.rb
# Rails.application.routes.draw do
  # get 'user_sessions/new'
  # get 'user_sessions/create'
#   get 'sessions/new'
#   get 'sessions/create'
#   get 'sessions/destroy'
#   resources :users, only: [:new, :create, :index, :show]
#   resources :sessions, only: [:new, :create, :destroy]
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Defines the root path route ("/")
#   # root "posts#index"
# end

Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/secret'
  get 'pages/dashboard'
  get '/rfqs/new', to: "rfqs#new"
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :rfqs, only: [:new, :create, :show, :edit] do
    resources :quotes, only: [:new, :create, :edit, :update]
  end
  resources :quotes
  resources :items, only: [:new, :create]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # Shows the login page
  def new
    @user = User.new
  end

  # User the created username and password to login the user
  def create
    # Finds the user by the username entered
    @user = User.find_by(name: params[:user][:name])

    # User.authenticate verifies the data entered, method provided by has_secure_password
    if @user && @user.authenticate(params[:user][:password])
      # Returns the user_id in the form of a encrypted cookie back to the user browser
      # Store the user_id so the next time when a controller checks the session, it knows the user is logged in
      session[:user_id] = @user.id
      redirect_to pages_dashboard_path
    else
      flash[:alert] = "Login Failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<!-- app/views/user_sessions/new.html.erb -->
<h1>Login Page</h1>

<%= form_with model: @user, url: user_sessions_path do |f| %>
    <div>
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :password %> <br>
        <%= f.password_field :password %>
    </div>
    <p>
        <%= f.submit 'Login' %>
    </p>
<% end %>